#!/usr/bin/env bash

#  author : sven zaugg
#    file : test_runner
# purpose : test suite runner for freetz-ng bash scripts
#
# for more infos about bats, see https://bats-core.readthedocs.io/

# FIXME SZA: library bats-core needs to be enhanced for excluding files (WIP)
declare -a EXCLUDE_TEST_FILES=( 
    template_test.bats
)

# invokes bats utility. tests under TEST_DIR are run.
# arguments:
#   TEST_DIR  directory which contains bats tests
invoke_bats() {
    [ -z $1 ] && { echo "missing argument TEST_DIR. abort."; return 1; }
    bats/modules/bats-core/bin/bats -T --verbose-run $1
}

invoke_bats bats
invoke_bats tools