#!/usr/bin/env bash

#  author : sven zaugg
#    file : test_runner
# purpose : test suite runner for freetz-ng bash scripts
#
# for more infos about bats, see https://bats-core.readthedocs.io/

# FIXME SZA: library bats-core needs to be enhanced for excluding files (WIP)
declare -a EXCLUDE_TEST_FILES=( 
    template_test.bats
)

# invokes bats utility. tests under following directories are run:
#   /bats
#   /tools
bats/modules/bats-core/bin/bats -T --print-output-on-failure --formatter pretty bats tools