#!/usr/bin/env bash

#  author : sven zaugg
#    file : test_runner
# purpose : test suite runner for freetz-ng bash scripts
#
# gets invoked by github workflow /.github/workflows/invoke_tests.yml

# @FUTURE #1 SZA: library bats-core needs to be enhanced for excluding files (WIP)
declare -a EXCLUDE_TEST_FILES=( 
    template_test.bats
)

# invokes bats utility. tests under following directories are run:
#   /bats
#   /tools
# bats/modules/bats-core/bin/bats -T --print-output-on-failure --formatter pretty bats tools

# @FUTURE #2 SZA: workaround because of @FUTURE #1
# calling tests directly so that bats/template_test.bats is excluded from running
bats/modules/bats-core/bin/bats \
    -T \
    --formatter pretty  \
    --print-output-on-failure \
    --show-output-of-passing-tests \
    bats/base_test_fixture.bats tools/push_firmware.bats

# @FUTURE SZA 
# --gather-test-outputs-in "reports/$(date +%Y-%m-%d_%H%M%S).log" \