#!/usr/bin/env bash

#  author : sven zaugg
#    file : template_test_fixture
# purpose : template for creating a test_fixture with bats

_base_setup() {
	load base_test_fixture
	__base_setup test/bats
}