#!/usr/bin/env bash

#  author : sven zaugg
#    file : testsuite.bash
# purpose : loads bats submodules and serves as basic test suite
#
# for more infos about bats, see https://bats-core.readthedocs.io/

_base_setup() {
	# load all external bats modules
	load '../tools/bats/bats-support/load' # bats-support/README.md
	load '../tools/bats/bats-assert/load'  # bats-assert/README.md
	load '../tools/bats/bats-file/load'    # bats-file/README.md
	load '../tools/bats/bats-mock/load'    # bats-mock/README.md

    	# make bash scripts in /tools visible for testsuite
    	PROJECT_ROOT="$( cd "$(dirname "$BATS_TEST_FILENAME" )/.." >/dev/null 2>&1 && pwd )"
   	PATH="$PROJECT_ROOT/tools:$PATH"
}
