#!/usr/bin/env bash

#  author : sven zaugg
#    file : test_fixture
# purpose : test_fixture for /tools

source $(dirname $BATS_TEST_FILENAME)/../bats/base_test_fixture

_base_setup() {
	__base_setup
}